# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{foreman_discovery}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Greg Sutcliffe"]
  s.date = %q{2013-02-27}
  s.description = %q{MaaS Discovery Plugin engine for Foreman }
  s.email = %q{gsutclif@redhat.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "app/controllers/foreman_discovery/hosts_controller_extensions.rb",
    "app/helpers/host_discovered_helper.rb",
    "app/models/host/discovered.rb",
    "app/views/hosts/discovered.html.erb",
    "app/views/hosts/_discovered_list.html.erb",
    "app/views/hosts/disc_show.html.erb",
    "config/routes.rb",
    "lib/foreman_discovery/engine.rb",
    "lib/foreman_discovery.rb",
    "README.md",
    "VERSION"
  ]
  s.homepage = %q{http://github.com/GregSutcliffe/foreman_discovery}
  s.licenses = ["GPL-3"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{MaaS Discovery Plugin for Foreman}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end
