#!/bin/bash
#
# vim: ts=2:sw=2:et
#
# Copyright (C) 2013 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA  02110-1301, USA.  A copy of the GNU General Public License is
# also available at http://www.gnu.org/copyleft/gpl.html.

ifs=$IFS
IFS=':'

files=$(find /usr -type f)
IFS=$ifs
for i in $files
do
  if [ `file $i | grep -c 'ELF'` -ne 0 ]; then
    if [ `ldd $i 2>/dev/null | grep -c 'not found'` -ne 0 ]; then
      echo "$i:"
      ldd $i 2>/dev/null | grep 'not found'
    fi
  fi
done
